version: '2'
services:
  parity:
    image: parity/parity:v2.3.5
    container_name: parity_rpc
    restart: always
    user: root
    command:
      --jsonrpc-interface all
      --nat "extip:[External IP]"
      --no-ipc
      --config /parity/config/parity.toml
      --min-gas-price 200000000000
      --no-secretstore
      --no-secretstore-http
    volumes:
      - evan-network-chain:/root/.local/share/io.parity.ethereum/
      - ./parity-config:/parity/config
      - ./testcore-config/testcore.json:/parity/config/testcore.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: nginx:1.15.9-alpine
    container_name: nginx_rpc
    restart: always
    command: /bin/sh -c "envsubst '$$SSL_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      - SSL_DOMAIN=core.evan.network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/ssl:/ssl
      - ./nginx-config/nginx.template.conf:/etc/nginx/nginx.conf.template
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  evan-network-chain:
