version: '2'
services:
  parity:
    image: parity/parity:v2.3.0
    container_name: parity_rpc
    user: root
    entrypoint: /home/parity/bin/parity
    restart: always
    command:
      --jsonrpc-interface all
      --nat "extip:[External IP]"
      --no-ipc
      --config /home/parity/parity-config/config/parity.toml
      --whisper
      --no-secretstore
      --no-secretstore-http
    volumes:
      - evan-network-chain:/home/parity/.local/share/io.parity.ethereum/
      - ./parity-config:/home/parity/parity-config/config
      - ./core-config/core.json:/home/parity/core-config/core.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: nginx:1.13.8-alpine
    container_name: nginx_rpc
    restart: always
    command: /bin/sh -c "envsubst '$$SSL_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      - SSL_DOMAIN=core.evan.network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/ssl:/ssl
      - ./nginx-config/nginx.template.conf:/etc/nginx/nginx.conf.template
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  evan-network-chain:
