version: '2'
services:
  parity:
    image: parity/parity:v2.1.3
    container_name: parity_rpc
    user: root
    entrypoint: /home/parity/bin/parity
    restart: always
    command: 
      --config /parity/config/parity.toml
      --jsonrpc-interface all
      --nat "extip:[External IP]"
      --no-dapps
      --whisper
      --no-secretstore
      --no-secretstore-http
      --no-ui
      --no-ipc      
    volumes:
      - evan-network-chain:/root/.local/share/io.parity.ethereum/
      - ./parity-config:/parity/config
      - ./testcore-config/testcore.json:/parity/config/testcore.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"        

  nginx:
    image: nginx:1.13.8-alpine
    container_name: nginx_rpc
    restart: always
    command: /bin/sh -c "envsubst '$$SSL_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      - SSL_DOMAIN=core.evan.network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/ssl:/ssl 
      - ./nginx-config/nginx.template.conf:/etc/nginx/nginx.conf.template
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"        

volumes:
  evan-network-chain:      
